dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: bPw8udHzp4WnFJ3v3c0+kfEDd74aHaFlu2bBk/XRqzCihjNEB2ffeGNXZwRmcotFNOVnunkvf7edxDCe9bHvO4I2lBJreCsGzHGBQMbiem0Kbbzbtgn2ThkwXxmpRfQcVpCnglmMcdRdHycFWtmkYiwZd2bDCilHIQGW4+IR9zKOk2wf3X91+q42nOXU1yMYwOTm5tf3J2ArBjTd0f5OxELGnYg2lKKGFl0Wf1Vz089yZgjfVMROEyM5Zz5TDhcwtG1lkSOr97iv56BYg4TXrrNRz1qvJvfYhKQ27XcBww7kRa9llt1kt9Vpyxg2SyZdd1OiZoinDfR3kbj60P2IclzoZPdlzJEZ7/AFKDkpNn4Jx3JjAONduaoayVks2rX8bJHx9nhq6LnwlL2sVtTuovrJbr3D7rEYcegzjCiqRnw5MY3YtoezSJ9Qfi+3QuBulX1CMh72pPtQCQouWPTbtH2+7oJTuG+aF3hP/EGUHpKlWTllMWBldrXzuzWE81dGCLU8ZwrgbbdQTJaBfcTpbBWcn+8u8O6puygrxEGSRu6FX3hzfOXnspVdQ7nRbGBBQ/xnGNGk4bp7jjRX6iktNYtG3DvfBE465O0/SFPeTsFUwDruygvbF6qgxieZ6l0mvYK7hz75b0MTpQ7OFz+eLuwZrdU5wuavs2ldxcAKz0o=
